### PR TITLE
FUCK THIS PROJECT, YOU GUYS FUCKED UP MY LIFE!!!!!

### PR DESCRIPTION
**Pull request by PedroxTheBest99**
I JUST CREATED A FILE CALLED "FUCK THIS" BUT I ONLY WANT TO YOU GUYS SHOW THIS MESSAGE TO MessengerFucker "FUCK THIS PROJECT, YOU GUYS FUCKED UP MY LIFE!!!!!!!!!!!!!!!!!!!!!!!!!!!"

### CODE REVIEW

**Comment by Nojus2001** [comment]
Yes, if someone removes yiu from a project your life is apperiantly "fucked up" by your logic and please don't create useless requests

**Comment by Craftplacer** [comment]
:clap: Reject :clap: this :clap: pull :clap: request :clap:

**Comment by PF94** [comment]
Pedrox has been blocked from even accessing XPorg's GitHub, I might plan to do this on Cloud Software if he does his ChrisChan-Level rants. 🤦‍♂ 

Pedrox, Your 2003page subsite was removed because
1. It wasn't that good
2. It was a advertisement for your channel that has a non-existing fanbase
3. You begged Memes to host your shitty bot, The only shit your bot was able to do was "Titties, Boobies".
4. The reaction of you joining 2003page was very negative.

**Comment by PF94** [comment]
Locking conversation to avoid any further drama

**Comment by PF94** [comment]
I've reverted the edits so verification can be better

**Pull request merged**
